version: '3'

services:
  django:
    build: .
    container_name: django
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/usr/src/app
    ports:
    - "8000:8000"
    depends_on:
      - pgdb

  pgdb:
    image: postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTDRES_USER=root
      - POSTGRES_PASSWORD=root
    container_name: pgdb
    volumes:
      - pgdbdata:/var/lib/postgressql/data

volumes:
  pgdbdata: null