---
# handlers file for deploy_apache_web
- name: Restart Apache2
  service: name=apache2 state=restarted
  when: ansible_os_family == "Debian"

- name: Restart HTTPD
  service: name=httpd state=restarted
  when: ansible_os_family == "RedHat"
