 ---
- name: Install Apache2
  hosts: all
  become: yes
  tasks:
  - name: Install Apache2
    apt: name=apache2 state=latest
  - name: Start Apache2 and enable on boot
    service: name=apache2 state=started enabled=yes
