---
- name: Install apache2 and my gaywebsite
  hosts: all
  become: yes
  vars:
   source_file: ./MyWebSite/index.html
   destin_file: /var/www/html


  tasks:
  - name: install apache2
    apt: name=apache2 state=latest

  - name: copy homepage to servers
    copy: src={{ source_file }} dest={{ destin_file }} mode=0555
    notify: Restart Apache2

  - name: start web servers
    service: name=apache2 state=started enabled=yes

  handlers:
  - name: Restart Apache2
    service: name=apache2 state=restarted
