---
- name: Delate Apache from servers
  hosts: all
  become: yes

  tasks:
  - name: Check what OS is on PC
    debug: var=ansible_os_family

  - block: #=== Block for DEBIAN ===
     - name: uninstall apache2 from DEBIAN
       apt: name=apache2 state=absent
    when: ansible_os_family == "Debian"

  - block: #=== Block for RedHat ===
     - name: uninstall httpd from RedHat
       yum: name=httpd state=absent
    when: ansible_os_family == "RedHat"
