---
- name: Ansible Erroe lesson
  hosts: all
  become: yes


  tasks:

  - name: task 1
    yum: name=treeeeee state=latest
    ignore_errors: yes
  - name: task
  - name: task 2
    shell: echo HelloWorld!
    register: result
    failed_when: results.rc == 0

#    failed_when: "'World' in results.stdout "

  - debug:
      var: results

  - name: task 3
    shell: echo From task 3!
