---

- name: Loop Playbook
  hosts: all
  become: yes

  tasks:
  - name: Say hello to all
    debug: msg="Hello {{ item }}"
    loop:
        - "Podlivich"
        - "Ochkorez"
        - "Huesos"
  - name: Loop untill
    shell: echo -n Z >> myfile.txt && cat myfile.txt
    register: output
    delay: 2
    retries: 10
    until: output.stdout.find("ZZZZ") == false

  - name: Print output
    debug:
      var: output.stdout
